config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'contact_us' => 'static_pages#contact_us'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Binay for President!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="orange ui large fixed inverted menu">
  <a class="header item" href="<%= root_path %>">Binay Website</a>
  <div class="ui dropdown link item">
    The Family
    <i class="dropdown icon"></i>
    <div class="menu">
      <a class="item"><img class="ui circular image" src="assets/jojo.jpg"></img>Jejomar "Jojo" Binay, Sr.</a>
      <a class="item"><img class="ui circular image" src="assets/nancy.jpg"></img>Maria Lourdes "Nancy" Binay</a>
      <a class="item"><img class="ui circular image" src="assets/junjun.jpg"></img>Jejomar Erwin "Junjun" Binay</a>
    </div>
  </div>
  <div class="right menu">
    <a class="item" href="<%= contact_us_path %>">Contact Us</a>
  </div>
</div>

<div id="main">
<%= yield %>
</div>

</body>
</html>

app/views/static_pages/contact_us.html.erb
<div class="ui container" style="margin-top: 100px">
  <h1>Contact Us</h1>
  <div class="ui card" style="padding: 20px">
    <h3>Lead Developer: Carl Araya</h3>
    <a href="https://www.facebook.com/carl.araya">Facebook</a>
    <a href="https://www.twitter.com/realctriplea">Twitter</a>
    Email Address: carl.araya256@gmail.com
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="scroller wow fadeIn" style="visibility: hidden">
  <div><img class="ui fluid image" src="assets/slide1.jpg"></img></div>
  <div><img class="ui fluid image" src="assets/slide2.jpg"></img></div>
  <div><img class="ui fluid image" src="assets/slide3.jpg"></img></div>
</div>

<div id="intro-text">
  <div class="ui grid">
    <div class="right aligned eight wide column wow fadeInLeftBig" data-wow-delay="1s">
      <h1 class="ui header">Kay Binay, gaganda ang buhay.</h1>
    </div>
    <div class="left aligned eight wide column wow fadeInRightBig" data-wow-delay="1s">
      <p class="ui header">Iboto natin si Binay sa darating na eleksyon.</p>
    </div>
  </div>
</div>